version: "3.7"
services:
  mongodb:
    image: mongo:latest    
    ports:
      - 27017:27017
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --maxmemory 500m --maxmemory-policy allkeys-lru

  service:
    image: shamyr/urlik/worker
    ports: 
      - 8000:80 
    environment:
      MONGO_URL: mongodb://mongo
      MONGO_DB_NAME: urlik
      REDIS_HOST: redis
      REDIS_PORT: 6379 
    build:
      context: .
      dockerfile: ./Dockerfile  

volumes:
  mongodata:
  redisdata: