name: CI

on:
  push:
    branches: 
      - 'releases/**'

jobs:
  buildAndPush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets. DOCKER_HUB_PASSWORD }}
          repository: shamyr/urlik-worker
          dockerfile: Dockerfile
          tags: latest
          tag_with_sha: true
